name: production

on:
  push:
    tags:
    - v*

jobs:
  lint:
    uses: spuxx-dev/ci-cd/.github/workflows/npm_lint.yml@v4.1.0

  test:
    uses: spuxx-dev/ci-cd/.github/workflows/npm_test-coverage.yml@v4.1.0

  release_image:
    needs:
    - lint
    - test
    uses: spuxx-dev/ci-cd/.github/workflows/docker_release_image.yml@v4.1.0
    with:
      latest: true
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
